name: Read hello.txt on Push

on:
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        - name: Checkout repository
          uses: actions/checkout@v3

           - name: Show hello.txt content
        run: |
          echo "Reading file..."
          cat hello.txt

